# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.v1 import api_pb2 as api_dot_v1_dot_api__pb2


class PipelineServiceStub(object):
    """-- services -----------------------------------------------------------------

    PipelineService exposes functionality for managing pipelines.
    Endpoints in this service can be used to create, fetch, modify or delete a
    pipeline. Entities connected to a pipeline (e.g. processors, connectors) can
    be fetched together with a pipeline, although they can not be modified
    through this service. Modifying these entities needs to be done through the
    service responsible for managing the corresponding entity.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListPipelines = channel.unary_unary(
                '/api.v1.PipelineService/ListPipelines',
                request_serializer=api_dot_v1_dot_api__pb2.ListPipelinesRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.ListPipelinesResponse.FromString,
                _registered_method=True)
        self.CreatePipeline = channel.unary_unary(
                '/api.v1.PipelineService/CreatePipeline',
                request_serializer=api_dot_v1_dot_api__pb2.CreatePipelineRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.CreatePipelineResponse.FromString,
                _registered_method=True)
        self.GetPipeline = channel.unary_unary(
                '/api.v1.PipelineService/GetPipeline',
                request_serializer=api_dot_v1_dot_api__pb2.GetPipelineRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.GetPipelineResponse.FromString,
                _registered_method=True)
        self.UpdatePipeline = channel.unary_unary(
                '/api.v1.PipelineService/UpdatePipeline',
                request_serializer=api_dot_v1_dot_api__pb2.UpdatePipelineRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.UpdatePipelineResponse.FromString,
                _registered_method=True)
        self.DeletePipeline = channel.unary_unary(
                '/api.v1.PipelineService/DeletePipeline',
                request_serializer=api_dot_v1_dot_api__pb2.DeletePipelineRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.DeletePipelineResponse.FromString,
                _registered_method=True)
        self.StartPipeline = channel.unary_unary(
                '/api.v1.PipelineService/StartPipeline',
                request_serializer=api_dot_v1_dot_api__pb2.StartPipelineRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.StartPipelineResponse.FromString,
                _registered_method=True)
        self.StopPipeline = channel.unary_unary(
                '/api.v1.PipelineService/StopPipeline',
                request_serializer=api_dot_v1_dot_api__pb2.StopPipelineRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.StopPipelineResponse.FromString,
                _registered_method=True)
        self.GetDLQ = channel.unary_unary(
                '/api.v1.PipelineService/GetDLQ',
                request_serializer=api_dot_v1_dot_api__pb2.GetDLQRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.GetDLQResponse.FromString,
                _registered_method=True)
        self.UpdateDLQ = channel.unary_unary(
                '/api.v1.PipelineService/UpdateDLQ',
                request_serializer=api_dot_v1_dot_api__pb2.UpdateDLQRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.UpdateDLQResponse.FromString,
                _registered_method=True)
        self.ExportPipeline = channel.unary_unary(
                '/api.v1.PipelineService/ExportPipeline',
                request_serializer=api_dot_v1_dot_api__pb2.ExportPipelineRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.ExportPipelineResponse.FromString,
                _registered_method=True)
        self.ImportPipeline = channel.unary_unary(
                '/api.v1.PipelineService/ImportPipeline',
                request_serializer=api_dot_v1_dot_api__pb2.ImportPipelineRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.ImportPipelineResponse.FromString,
                _registered_method=True)
        self.PlanPipeline = channel.unary_unary(
                '/api.v1.PipelineService/PlanPipeline',
                request_serializer=api_dot_v1_dot_api__pb2.PlanPipelineRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.PlanPipelineResponse.FromString,
                _registered_method=True)
        self.ApplyPipeline = channel.unary_unary(
                '/api.v1.PipelineService/ApplyPipeline',
                request_serializer=api_dot_v1_dot_api__pb2.ApplyPipelineRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.ApplyPipelineResponse.FromString,
                _registered_method=True)


class PipelineServiceServicer(object):
    """-- services -----------------------------------------------------------------

    PipelineService exposes functionality for managing pipelines.
    Endpoints in this service can be used to create, fetch, modify or delete a
    pipeline. Entities connected to a pipeline (e.g. processors, connectors) can
    be fetched together with a pipeline, although they can not be modified
    through this service. Modifying these entities needs to be done through the
    service responsible for managing the corresponding entity.
    """

    def ListPipelines(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartPipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopPipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDLQ(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDLQ(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportPipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportPipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlanPipeline(self, request, context):
        """PlanPipeline computes the diff needed to reconcile a pipeline's
        currently stored state with the desired config, without applying
        anything (read-only, safe to call against a running pipeline). See
        docs/design-documents/20260708-live-server-deploy-apply.md.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyPipeline(self, request, context):
        """ApplyPipeline executes the plan for a desired pipeline config, gated on
        the caller presenting the hash of the plan it reviewed (a stale hash is
        refused, never partially applied). Against a running pipeline whose plan
        includes a restart-class change, this requires the server to have been
        started with the live-restart-apply operator flag — see
        docs/design-documents/20260708-live-server-deploy-apply.md and
        docs/operations/live-restart-apply.md.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PipelineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListPipelines': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPipelines,
                    request_deserializer=api_dot_v1_dot_api__pb2.ListPipelinesRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.ListPipelinesResponse.SerializeToString,
            ),
            'CreatePipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePipeline,
                    request_deserializer=api_dot_v1_dot_api__pb2.CreatePipelineRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.CreatePipelineResponse.SerializeToString,
            ),
            'GetPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPipeline,
                    request_deserializer=api_dot_v1_dot_api__pb2.GetPipelineRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.GetPipelineResponse.SerializeToString,
            ),
            'UpdatePipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePipeline,
                    request_deserializer=api_dot_v1_dot_api__pb2.UpdatePipelineRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.UpdatePipelineResponse.SerializeToString,
            ),
            'DeletePipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePipeline,
                    request_deserializer=api_dot_v1_dot_api__pb2.DeletePipelineRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.DeletePipelineResponse.SerializeToString,
            ),
            'StartPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.StartPipeline,
                    request_deserializer=api_dot_v1_dot_api__pb2.StartPipelineRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.StartPipelineResponse.SerializeToString,
            ),
            'StopPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.StopPipeline,
                    request_deserializer=api_dot_v1_dot_api__pb2.StopPipelineRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.StopPipelineResponse.SerializeToString,
            ),
            'GetDLQ': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDLQ,
                    request_deserializer=api_dot_v1_dot_api__pb2.GetDLQRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.GetDLQResponse.SerializeToString,
            ),
            'UpdateDLQ': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDLQ,
                    request_deserializer=api_dot_v1_dot_api__pb2.UpdateDLQRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.UpdateDLQResponse.SerializeToString,
            ),
            'ExportPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportPipeline,
                    request_deserializer=api_dot_v1_dot_api__pb2.ExportPipelineRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.ExportPipelineResponse.SerializeToString,
            ),
            'ImportPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportPipeline,
                    request_deserializer=api_dot_v1_dot_api__pb2.ImportPipelineRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.ImportPipelineResponse.SerializeToString,
            ),
            'PlanPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.PlanPipeline,
                    request_deserializer=api_dot_v1_dot_api__pb2.PlanPipelineRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.PlanPipelineResponse.SerializeToString,
            ),
            'ApplyPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyPipeline,
                    request_deserializer=api_dot_v1_dot_api__pb2.ApplyPipelineRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.ApplyPipelineResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.v1.PipelineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.v1.PipelineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PipelineService(object):
    """-- services -----------------------------------------------------------------

    PipelineService exposes functionality for managing pipelines.
    Endpoints in this service can be used to create, fetch, modify or delete a
    pipeline. Entities connected to a pipeline (e.g. processors, connectors) can
    be fetched together with a pipeline, although they can not be modified
    through this service. Modifying these entities needs to be done through the
    service responsible for managing the corresponding entity.
    """

    @staticmethod
    def ListPipelines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.PipelineService/ListPipelines',
            api_dot_v1_dot_api__pb2.ListPipelinesRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.ListPipelinesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.PipelineService/CreatePipeline',
            api_dot_v1_dot_api__pb2.CreatePipelineRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.CreatePipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.PipelineService/GetPipeline',
            api_dot_v1_dot_api__pb2.GetPipelineRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.GetPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.PipelineService/UpdatePipeline',
            api_dot_v1_dot_api__pb2.UpdatePipelineRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.UpdatePipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.PipelineService/DeletePipeline',
            api_dot_v1_dot_api__pb2.DeletePipelineRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.DeletePipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.PipelineService/StartPipeline',
            api_dot_v1_dot_api__pb2.StartPipelineRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.StartPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.PipelineService/StopPipeline',
            api_dot_v1_dot_api__pb2.StopPipelineRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.StopPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDLQ(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.PipelineService/GetDLQ',
            api_dot_v1_dot_api__pb2.GetDLQRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.GetDLQResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDLQ(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.PipelineService/UpdateDLQ',
            api_dot_v1_dot_api__pb2.UpdateDLQRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.UpdateDLQResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.PipelineService/ExportPipeline',
            api_dot_v1_dot_api__pb2.ExportPipelineRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.ExportPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.PipelineService/ImportPipeline',
            api_dot_v1_dot_api__pb2.ImportPipelineRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.ImportPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlanPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.PipelineService/PlanPipeline',
            api_dot_v1_dot_api__pb2.PlanPipelineRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.PlanPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.PipelineService/ApplyPipeline',
            api_dot_v1_dot_api__pb2.ApplyPipelineRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.ApplyPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConnectorServiceStub(object):
    """ConnectorService exposes CRUD functionality for managing connectors.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListConnectors = channel.unary_unary(
                '/api.v1.ConnectorService/ListConnectors',
                request_serializer=api_dot_v1_dot_api__pb2.ListConnectorsRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.ListConnectorsResponse.FromString,
                _registered_method=True)
        self.InspectConnector = channel.unary_stream(
                '/api.v1.ConnectorService/InspectConnector',
                request_serializer=api_dot_v1_dot_api__pb2.InspectConnectorRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.InspectConnectorResponse.FromString,
                _registered_method=True)
        self.GetConnector = channel.unary_unary(
                '/api.v1.ConnectorService/GetConnector',
                request_serializer=api_dot_v1_dot_api__pb2.GetConnectorRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.GetConnectorResponse.FromString,
                _registered_method=True)
        self.CreateConnector = channel.unary_unary(
                '/api.v1.ConnectorService/CreateConnector',
                request_serializer=api_dot_v1_dot_api__pb2.CreateConnectorRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.CreateConnectorResponse.FromString,
                _registered_method=True)
        self.ValidateConnector = channel.unary_unary(
                '/api.v1.ConnectorService/ValidateConnector',
                request_serializer=api_dot_v1_dot_api__pb2.ValidateConnectorRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.ValidateConnectorResponse.FromString,
                _registered_method=True)
        self.UpdateConnector = channel.unary_unary(
                '/api.v1.ConnectorService/UpdateConnector',
                request_serializer=api_dot_v1_dot_api__pb2.UpdateConnectorRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.UpdateConnectorResponse.FromString,
                _registered_method=True)
        self.DeleteConnector = channel.unary_unary(
                '/api.v1.ConnectorService/DeleteConnector',
                request_serializer=api_dot_v1_dot_api__pb2.DeleteConnectorRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.DeleteConnectorResponse.FromString,
                _registered_method=True)
        self.ListConnectorPlugins = channel.unary_unary(
                '/api.v1.ConnectorService/ListConnectorPlugins',
                request_serializer=api_dot_v1_dot_api__pb2.ListConnectorPluginsRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.ListConnectorPluginsResponse.FromString,
                _registered_method=True)


class ConnectorServiceServicer(object):
    """ConnectorService exposes CRUD functionality for managing connectors.
    """

    def ListConnectors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InspectConnector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConnector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateConnector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateConnector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConnector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteConnector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConnectorPlugins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListConnectors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConnectors,
                    request_deserializer=api_dot_v1_dot_api__pb2.ListConnectorsRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.ListConnectorsResponse.SerializeToString,
            ),
            'InspectConnector': grpc.unary_stream_rpc_method_handler(
                    servicer.InspectConnector,
                    request_deserializer=api_dot_v1_dot_api__pb2.InspectConnectorRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.InspectConnectorResponse.SerializeToString,
            ),
            'GetConnector': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConnector,
                    request_deserializer=api_dot_v1_dot_api__pb2.GetConnectorRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.GetConnectorResponse.SerializeToString,
            ),
            'CreateConnector': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateConnector,
                    request_deserializer=api_dot_v1_dot_api__pb2.CreateConnectorRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.CreateConnectorResponse.SerializeToString,
            ),
            'ValidateConnector': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateConnector,
                    request_deserializer=api_dot_v1_dot_api__pb2.ValidateConnectorRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.ValidateConnectorResponse.SerializeToString,
            ),
            'UpdateConnector': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConnector,
                    request_deserializer=api_dot_v1_dot_api__pb2.UpdateConnectorRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.UpdateConnectorResponse.SerializeToString,
            ),
            'DeleteConnector': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteConnector,
                    request_deserializer=api_dot_v1_dot_api__pb2.DeleteConnectorRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.DeleteConnectorResponse.SerializeToString,
            ),
            'ListConnectorPlugins': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConnectorPlugins,
                    request_deserializer=api_dot_v1_dot_api__pb2.ListConnectorPluginsRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.ListConnectorPluginsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.v1.ConnectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.v1.ConnectorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConnectorService(object):
    """ConnectorService exposes CRUD functionality for managing connectors.
    """

    @staticmethod
    def ListConnectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.ConnectorService/ListConnectors',
            api_dot_v1_dot_api__pb2.ListConnectorsRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.ListConnectorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InspectConnector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/api.v1.ConnectorService/InspectConnector',
            api_dot_v1_dot_api__pb2.InspectConnectorRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.InspectConnectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConnector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.ConnectorService/GetConnector',
            api_dot_v1_dot_api__pb2.GetConnectorRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.GetConnectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateConnector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.ConnectorService/CreateConnector',
            api_dot_v1_dot_api__pb2.CreateConnectorRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.CreateConnectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateConnector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.ConnectorService/ValidateConnector',
            api_dot_v1_dot_api__pb2.ValidateConnectorRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.ValidateConnectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConnector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.ConnectorService/UpdateConnector',
            api_dot_v1_dot_api__pb2.UpdateConnectorRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.UpdateConnectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteConnector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.ConnectorService/DeleteConnector',
            api_dot_v1_dot_api__pb2.DeleteConnectorRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.DeleteConnectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConnectorPlugins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.ConnectorService/ListConnectorPlugins',
            api_dot_v1_dot_api__pb2.ListConnectorPluginsRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.ListConnectorPluginsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ProcessorServiceStub(object):
    """ProcessorService exposes CRUD functionality for managing processors.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListProcessors = channel.unary_unary(
                '/api.v1.ProcessorService/ListProcessors',
                request_serializer=api_dot_v1_dot_api__pb2.ListProcessorsRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.ListProcessorsResponse.FromString,
                _registered_method=True)
        self.InspectProcessorIn = channel.unary_stream(
                '/api.v1.ProcessorService/InspectProcessorIn',
                request_serializer=api_dot_v1_dot_api__pb2.InspectProcessorInRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.InspectProcessorInResponse.FromString,
                _registered_method=True)
        self.InspectProcessorOut = channel.unary_stream(
                '/api.v1.ProcessorService/InspectProcessorOut',
                request_serializer=api_dot_v1_dot_api__pb2.InspectProcessorOutRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.InspectProcessorOutResponse.FromString,
                _registered_method=True)
        self.GetProcessor = channel.unary_unary(
                '/api.v1.ProcessorService/GetProcessor',
                request_serializer=api_dot_v1_dot_api__pb2.GetProcessorRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.GetProcessorResponse.FromString,
                _registered_method=True)
        self.CreateProcessor = channel.unary_unary(
                '/api.v1.ProcessorService/CreateProcessor',
                request_serializer=api_dot_v1_dot_api__pb2.CreateProcessorRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.CreateProcessorResponse.FromString,
                _registered_method=True)
        self.UpdateProcessor = channel.unary_unary(
                '/api.v1.ProcessorService/UpdateProcessor',
                request_serializer=api_dot_v1_dot_api__pb2.UpdateProcessorRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.UpdateProcessorResponse.FromString,
                _registered_method=True)
        self.DeleteProcessor = channel.unary_unary(
                '/api.v1.ProcessorService/DeleteProcessor',
                request_serializer=api_dot_v1_dot_api__pb2.DeleteProcessorRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.DeleteProcessorResponse.FromString,
                _registered_method=True)
        self.ListProcessorPlugins = channel.unary_unary(
                '/api.v1.ProcessorService/ListProcessorPlugins',
                request_serializer=api_dot_v1_dot_api__pb2.ListProcessorPluginsRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.ListProcessorPluginsResponse.FromString,
                _registered_method=True)


class ProcessorServiceServicer(object):
    """ProcessorService exposes CRUD functionality for managing processors.
    """

    def ListProcessors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InspectProcessorIn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InspectProcessorOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcessor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProcessor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProcessor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProcessor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProcessorPlugins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcessorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListProcessors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProcessors,
                    request_deserializer=api_dot_v1_dot_api__pb2.ListProcessorsRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.ListProcessorsResponse.SerializeToString,
            ),
            'InspectProcessorIn': grpc.unary_stream_rpc_method_handler(
                    servicer.InspectProcessorIn,
                    request_deserializer=api_dot_v1_dot_api__pb2.InspectProcessorInRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.InspectProcessorInResponse.SerializeToString,
            ),
            'InspectProcessorOut': grpc.unary_stream_rpc_method_handler(
                    servicer.InspectProcessorOut,
                    request_deserializer=api_dot_v1_dot_api__pb2.InspectProcessorOutRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.InspectProcessorOutResponse.SerializeToString,
            ),
            'GetProcessor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcessor,
                    request_deserializer=api_dot_v1_dot_api__pb2.GetProcessorRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.GetProcessorResponse.SerializeToString,
            ),
            'CreateProcessor': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProcessor,
                    request_deserializer=api_dot_v1_dot_api__pb2.CreateProcessorRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.CreateProcessorResponse.SerializeToString,
            ),
            'UpdateProcessor': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProcessor,
                    request_deserializer=api_dot_v1_dot_api__pb2.UpdateProcessorRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.UpdateProcessorResponse.SerializeToString,
            ),
            'DeleteProcessor': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProcessor,
                    request_deserializer=api_dot_v1_dot_api__pb2.DeleteProcessorRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.DeleteProcessorResponse.SerializeToString,
            ),
            'ListProcessorPlugins': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProcessorPlugins,
                    request_deserializer=api_dot_v1_dot_api__pb2.ListProcessorPluginsRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.ListProcessorPluginsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.v1.ProcessorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.v1.ProcessorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProcessorService(object):
    """ProcessorService exposes CRUD functionality for managing processors.
    """

    @staticmethod
    def ListProcessors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.ProcessorService/ListProcessors',
            api_dot_v1_dot_api__pb2.ListProcessorsRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.ListProcessorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InspectProcessorIn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/api.v1.ProcessorService/InspectProcessorIn',
            api_dot_v1_dot_api__pb2.InspectProcessorInRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.InspectProcessorInResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InspectProcessorOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/api.v1.ProcessorService/InspectProcessorOut',
            api_dot_v1_dot_api__pb2.InspectProcessorOutRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.InspectProcessorOutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProcessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.ProcessorService/GetProcessor',
            api_dot_v1_dot_api__pb2.GetProcessorRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.GetProcessorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProcessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.ProcessorService/CreateProcessor',
            api_dot_v1_dot_api__pb2.CreateProcessorRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.CreateProcessorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProcessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.ProcessorService/UpdateProcessor',
            api_dot_v1_dot_api__pb2.UpdateProcessorRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.UpdateProcessorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProcessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.ProcessorService/DeleteProcessor',
            api_dot_v1_dot_api__pb2.DeleteProcessorRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.DeleteProcessorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProcessorPlugins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.ProcessorService/ListProcessorPlugins',
            api_dot_v1_dot_api__pb2.ListProcessorPluginsRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.ListProcessorPluginsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class InformationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfo = channel.unary_unary(
                '/api.v1.InformationService/GetInfo',
                request_serializer=api_dot_v1_dot_api__pb2.GetInfoRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.GetInfoResponse.FromString,
                _registered_method=True)


class InformationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InformationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=api_dot_v1_dot_api__pb2.GetInfoRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.GetInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.v1.InformationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.v1.InformationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InformationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.InformationService/GetInfo',
            api_dot_v1_dot_api__pb2.GetInfoRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.GetInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PluginServiceStub(object):
    """Deprecated: use ConnectorService and ProcessorService instead.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListPlugins = channel.unary_unary(
                '/api.v1.PluginService/ListPlugins',
                request_serializer=api_dot_v1_dot_api__pb2.ListPluginsRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_api__pb2.ListPluginsResponse.FromString,
                _registered_method=True)


class PluginServiceServicer(object):
    """Deprecated: use ConnectorService and ProcessorService instead.
    """

    def ListPlugins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListPlugins': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlugins,
                    request_deserializer=api_dot_v1_dot_api__pb2.ListPluginsRequest.FromString,
                    response_serializer=api_dot_v1_dot_api__pb2.ListPluginsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.v1.PluginService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.v1.PluginService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginService(object):
    """Deprecated: use ConnectorService and ProcessorService instead.
    """

    @staticmethod
    def ListPlugins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.PluginService/ListPlugins',
            api_dot_v1_dot_api__pb2.ListPluginsRequest.SerializeToString,
            api_dot_v1_dot_api__pb2.ListPluginsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
